name: Windows

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: libCURL
        id: get_libcurl
        uses: ./.github/actions/windows-setup-curl
        with:
          architecture: 'win64'
      - name: Copy Libcurl
        id: prepare_libcurl
        env:
          CURL_PATH: ${{ steps.get_libcurl.outputs.curl_path }}
        run: |
          cp $env:CURL_PATH/bin/libcurl-x64.dll $env:GITHUB_WORKSPACE/libcurl-x64.dll
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - name: Download llama.cpp
        uses: robinraju/release-downloader@v1
        with:
            repository: 'ggml-org/llama.cpp'
            latest: true
            fileName: 'llama-*-bin-win-cpu-x64.zip'
            out-file-path: '.'
            extract: true
      - name: Set test library location
        run: |
            echo "${env:GITHUB_WORKSPACE}" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
            echo "YZMA_LIB=${env:GITHUB_WORKSPACE}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Run tests
        run: |
            dir
            go test -v ./...
